import { Account } from './account';
import { Contact } from './contact';

export class Invoice {
invoiceId:String;
createdBy? :String;
modifiedBy? :String;
createdOnBehalfBy? :String;
modifiedOnBehalfBy? :String;
ownerIdType? :String;
ownerId? :String;
owningBusinessUnit? :String;
owningUser? :String;
owningTeam? :String;
emailAddress? :String;
name:String;
processId? :String;
stageId? :String;
traversedPath? :String;
billToCity? :String;
billToComposite? :String;
billToCountry? :String;
billToFax? :String;
billToLine1? :String;
billToLine2? :String;
billToLine3? :String;
billToName? :String;
billToPostalCode? :String;
billToStateOrProvince? :String;
billToTelephone? :String;
customerIdType? :String;
customerId? :String;
description? :String;
transactionCurrencyId? :String;
invoiceNumber? :String;
opportunityId? :String;
paymentTermsCodedisplay? :String;
priceLevelId? :String;
pricingErrorCodedisplay? :String;
priorityCodedisplay? :String;
salesOrderId? :String;
shippingMethodCodedisplay? :String;
shipToCity? :String;
shipToComposite? :String;
shipToCountry? :String;
shipToFax? :String;
shipToFreightTermsCodedisplay? :String;
shipToLine1? :String;
shipToLine2? :String;
shipToLine3? :String;
shipToName? :String;
shipToPostalCode? :String;
shipToStateOrProvince? :String;
shipToTelephone? :String;
stateCodedisplay? :String;
statusCodedisplay? :String;
sLAId? :String;
sLAInvokedId? :String;
entityImageId? :String;
billToContactName? :String;
orderTypedisplay? :String;
projectInvoiceStatusdisplay? :String;
createdOn? : Date;
modifiedOn? : Date;
overriddenCreatedOn? : Date;
importSequenceNumber? :Number;
timeZoneRuleVersionNumber? :Number;
uTCConversionTimeZoneCode? :Number;
versionNumber? :Number;
dateDelivered? : Date;
discountAmount? :Number;
exchangeRate? :Number;
discountAmountBase? :Number;
discountPercentage? :Number;
dueDate? : Date;
freightAmount? :Number;
freightAmountBase? :Number;
isPriceLocked? :Number;
lastBackofficeSubmit? : Date;
paymentTermsCode? :Number;
pricingErrorCode? :Number;
priorityCode? :Number;
shippingMethodCode? :Number;
shipToFreightTermsCode? :Number;
stateCode? :Number;
statusCode? :Number;
totalAmount? :Number;
totalAmountBase? :Number;
totalAmountLessFreight? :Number;
totalAmountLessFreightBase? :Number;
totalDiscountAmount? :Number;
totalDiscountAmountBase? :Number;
totalLineItemAmount? :Number;
totalLineItemAmountBase? :Number;
totalLineItemDiscountAmount? :Number;
totalLineItemDiscountAmountBase? :Number;
totalTax? :Number;
totalTaxBase? :Number;
willCall? :Number;
onHoldTime? :Number;
lastOnHoldTime? : Date;
hasCorrections? :Number;
orderType? :Number;
projectInvoiceStatus? :Number;
accountId? :Account;
contactId? :Contact;
}

