import { Account } from './account';
import { Paymentschedule } from './paymentschedule';
export class Transactions {
createdOn? : Date;
createdBy? :String;
modifiedOn? :Date;
modifiedBy? :String;
createdOnBehalfBy? :String;
modifiedOnBehalfBy? :String;
overriddenCreatedOn? : Date;
importSequenceNumber? :Number;
ownerIdType? :String;
ownerId? :String;
owningBusinessUnit? :String;
owningUser? :String;
owningTeam? :String;
timeZoneRuleVersionNumber? :Number;
versionNumber? :Number;
transactionId :String;
stateCode? :Number;
stateCodedisplay? :String;
statusCode? :Number;
statusCodedisplay? :String;
name :String;
adjustmentComment? :String;
adjustmentReason? :Number;
adjustmentReasondisplay? :String;
adjustmentType? :Number;
adjustmentTypedisplay? :String;
amount? :Number;
transactionCurrencyId? :String;
exchangeRate? :Number;
amountBase? :Number;
anonymity? :Number;
anonymityDisplay? :String;
bookDate? : Date;
dataEntryReference? :String;
dataEntrySource? :Number;
dataEntrySourcedisplay? :String;
effectiveCampaignId? :String;
effectiveSourceCode? :String;
exchangeRateDate? : Date;
isAdjusted? :Number;
originalTxnAdjustedId? :String;
originatingCampaignId? :String;
originatingSourceCode? :String;
postedDate? : Date;
receivedDate? : Date;
transactionPaymentMethodId? :String;
currencyValueDate? : Date;
description? :String;
disbursementChannelId? :String;
financeTypeId? :String;
flowTypeId? :String;
humanitarian? :Number;
providerActivityIdentifier? :String;
providerOrganizationId? :String;
recipientActivityIdentifier? :String;
recipientCountryDescription? :String;
recipientCountryId? :String;
recipientOrganizationId? :String;
recipientRegionDescription? :String;
recipientRegionId? :String;
tiedStatusId? :String;
transactionReceiptOnAccountId :Account;
transactionPaymentScheduleId: Paymentschedule;
utcconversionTimeZoneCode? :Number;
}
